# Generated by Django 4.2.1 on 2023-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('proc_ADM', models.CharField(max_length=50)),
                ('tcaNum', models.CharField(max_length=50)),
                ('compromitente', models.CharField(max_length=100)),
                ('cpfcnpj', models.CharField(max_length=50)),
                ('insc_CAD', models.CharField(max_length=5)),
                ('endereco', models.CharField(max_length=100)),
                ('quadra', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=5)),
                ('anuencia_CETESB', models.CharField(max_length=20)),
                ('anuencia_CONDEMA', models.CharField(max_length=20)),
                ('observacao', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('transplante', models.CharField(max_length=50)),
                ('vegetacao', models.CharField(max_length=50)),
                ('estagio', models.CharField(max_length=50)),
                ('app1', models.CharField(max_length=20)),
                ('app2', models.CharField(max_length=20)),
                ('reserva', models.CharField(max_length=20)),
                ('restricao', models.CharField(max_length=50)),
            ],
        ),
    ]
